<a href="https://colab.research.google.com/github/IrfanSadik13/Spam-classifier-/blob/main/Spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:

df = pd.read_csv('/content/drive/MyDrive/Datasets/spam.csv', encoding='ISO-8859-1')

In [ ]:
df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],inplace=True)

In [ ]:

df.rename(columns={"v1": "target", "v2": "text"}, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [ ]:
df["target"]=encoder.fit_transform(df["target"])

In [ ]:
df=df.drop_duplicates(keep="first")

In [ ]:
df.shape

(5169, 2)

In [ ]:
import nltk

In [ ]:

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
df["num_characters"]=df["text"].apply(len)

In [ ]:
df["num_words"]=df["text"].apply(lambda x:len(nltk.word_tokenize(x)))

In [ ]:
df["num_sentences"]=df["text"].apply(lambda x:len(nltk.sent_tokenize(x)))

In [ ]:
df.describe()

target  num_characters    num_words  num_sentences
count  5169.000000     5169.000000  5169.000000    5169.000000
mean      0.126330       78.977945    18.455794       1.965564
std       0.332253       58.236293    13.324758       1.448541
min       0.000000        2.000000     1.000000       1.000000
25%       0.000000       36.000000     9.000000       1.000000
50%       0.000000       60.000000    15.000000       1.000000
75%       0.000000      117.000000    26.000000       2.000000
max       1.000000      910.000000   220.000000      38.000000

In [ ]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)

    y = []
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))


    return " ".join(y)

In [ ]:

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import string

# Download necessary resources (run only once)
nltk.download('punkt')
nltk.download('stopwords')

ps = PorterStemmer()

def transform_text(text):
    text = text.lower()
    text = word_tokenize(text)

    y = []
    for i in text:
        if i.isalnum():  # Keep only alphanumeric tokens
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))

    return " ".join(y)

#df["text"] = df["text"].apply(transform_text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
df["transformed_text"]=df["text"].apply(transform_text)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [ ]:
x = tfidf.fit_transform(df['transformed_text']).toarray()

In [ ]:
y=df["target"].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

# Train GaussianNB
gnb.fit(x_train, y_train)

# Predictions
y_pred_gnb = gnb.predict(x_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_gnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gnb))
print("Precision:", precision_score(y_test, y_pred_gnb))

Accuracy: 0.8694390715667312
Confusion Matrix:
 [[788 108]
 [ 27 111]]
Precision: 0.5068493150684932


In [ ]:
mnb.fit(x_train, y_train)
y_pred_mnb = mnb.predict(x_test)

print("MultinomialNB Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_mnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_mnb))
print("Precision:", precision_score(y_test, y_pred_mnb))
print("-" * 50)

MultinomialNB Results:
Accuracy: 0.9709864603481625
Confusion Matrix:
 [[896   0]
 [ 30 108]]
Precision: 1.0
--------------------------------------------------


In [ ]:
bnb.fit(x_train, y_train)
y_pred_bnb = bnb.predict(x_test)

print("BernoulliNB Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_bnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bnb))
print("Precision:", precision_score(y_test, y_pred_bnb))
print("-" * 50)

BernoulliNB Results:
Accuracy: 0.9835589941972921
Confusion Matrix:
 [[895   1]
 [ 16 122]]
Precision: 0.991869918699187
--------------------------------------------------


In [ ]:
import pickle
pickle.dump(tfidf,open("vectorizer.pkl","wb"))
pickle.dump(mnb,open("model.pkl","wb"))

In [ ]:
input_sms = ""
transformed_sms = transform_text(input_sms)
vector_input = tfidf.transform([transformed_sms])
vector_input

<1x3000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [ ]:
result = mnb.predict(vector_input)[0]

In [ ]:
def prediction(text):
    input_sms = ""
    transformed_sms = transform_text(input_sms)
    vector_input = tfidf.transform([transformed_sms])
    result = mnb.predict(vector_input)[0]
    if result==0:        print("not spam")
    else:
        print("spam")

In [ ]:
prediction("Your PayPal account has been suspended. Verify your details immediately")

not spam


In [ ]:

# New set of sample emails (spam = 1, ham = 0)
emails = [
    # SPAM Emails
    ("Win a brand new iPhone! Click the link to enter the contest now.", 1),
    ("Your PayPal account has been suspended. Verify your details immediately.", 1),
    ("Act now! Get 90% off on all products for the next 24 hours.", 1),
    ("You've been pre-approved for a $10,000 loan. No credit check required.", 1),
    ("Exclusive offer just for you! Get free Bitcoin by signing up today.", 1),
    ("Hi, I'm a prince from Nigeria, and I need your help transferring $1 million.", 1),
    ("Urgent: Your social security number has been compromised. Call now!", 1),
    ("Special promo: Subscribe today and get lifetime access for free.", 1),
    ("Increase your followers instantly! Buy 10,000 followers for only $5.", 1),
    ("Final reminder: Your car warranty is about to expire. Renew now!", 1),

    # HAM Emails
    ("Hey, can you send me the notes from yesterday’s lecture?", 0),
    ("Your Amazon order has been shipped and will arrive soon.", 0),
    ("Reminder: Your electricity bill is due next week.", 0),
    ("The meeting has been moved to 2 PM. Let me know if that works.", 0),
    ("Can you review the document and share your feedback?", 0),
    ("Happy birthday! Hope you have a fantastic day ahead.", 0),
    ("Let's schedule a call for tomorrow morning.", 0),
    ("Looking forward to catching up this weekend!", 0),
    ("Your flight has been rescheduled. Please check your email for details.", 0),
    ("The code implementation looks good. Just a few minor fixes needed.", 0)
]

# Function to check correctness
def evaluate_model(prediction_function):
    correct = 0
    total = len(emails)

    for email, actual_label in emails:
        predicted_label = 1 if prediction_function(email) == "Spam" else 0
        is_correct = "✅ Correct" if predicted_label == actual_label else "❌ Wrong"

        print(f"Email: {email}")
        print(f"Predicted: {'Spam' if predicted_label else 'Ham'} | Actual: {'Spam' if actual_label else 'Ham'} | {is_correct}\n")

        correct += (predicted_label == actual_label)

    accuracy = (correct / total) * 100
    print(f"Model Accuracy: {accuracy:.2f}%")

# Run evaluation
evaluate_model(prediction)

not spam
Email: Win a brand new iPhone! Click the link to enter the contest now.
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: Your PayPal account has been suspended. Verify your details immediately.
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: Act now! Get 90% off on all products for the next 24 hours.
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: You've been pre-approved for a $10,000 loan. No credit check required.
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: Exclusive offer just for you! Get free Bitcoin by signing up today.
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: Hi, I'm a prince from Nigeria, and I need your help transferring $1 million.
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: Urgent: Your social security number has been compromised. Call now!
Predicted: Ham | Actual: Spam | ❌ Wrong

not spam
Email: Special promo: Subscribe today and get lifetime access for free.
Predicted: Ham | Actual: Spam | ❌ Wron