<a href="https://colab.research.google.com/github/IrfanSadik13/Spam-classifier-/blob/main/Spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:

df = pd.read_csv('/content/drive/MyDrive/Datasets/spam.csv', encoding='ISO-8859-1')

In [ ]:
df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],inplace=True)

In [ ]:

df.rename(columns={"v1": "target", "v2": "text"}, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [ ]:
df["target"]=encoder.fit_transform(df["target"])

In [ ]:
df=df.drop_duplicates(keep="first")

In [ ]:
df.shape

(5169, 2)

In [ ]:
import nltk

In [ ]:

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
df["num_characters"]=df["text"].apply(len)

In [ ]:
df["num_words"]=df["text"].apply(lambda x:len(nltk.word_tokenize(x)))

In [ ]:
df["num_sentences"]=df["text"].apply(lambda x:len(nltk.sent_tokenize(x)))

In [ ]:
df.describe()

target  num_characters    num_words  num_sentences
count  5169.000000     5169.000000  5169.000000    5169.000000
mean      0.126330       78.977945    18.455794       1.965564
std       0.332253       58.236293    13.324758       1.448541
min       0.000000        2.000000     1.000000       1.000000
25%       0.000000       36.000000     9.000000       1.000000
50%       0.000000       60.000000    15.000000       1.000000
75%       0.000000      117.000000    26.000000       2.000000
max       1.000000      910.000000   220.000000      38.000000

In [ ]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)

    y = []
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))


    return " ".join(y)

In [ ]:

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import string

# Download necessary resources (run only once)
nltk.download('punkt')
nltk.download('stopwords')

ps = PorterStemmer()

def transform_text(text):
    text = text.lower()
    text = word_tokenize(text)

    y = []
    for i in text:
        if i.isalnum():  # Keep only alphanumeric tokens
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))

    return " ".join(y)

#df["text"] = df["text"].apply(transform_text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
df["transformed_text"]=df["text"].apply(transform_text)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [ ]:
x = tfidf.fit_transform(df['transformed_text']).toarray()

In [ ]:
y=df["target"].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

# Train GaussianNB
gnb.fit(x_train, y_train)

# Predictions
y_pred_gnb = gnb.predict(x_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_gnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gnb))
print("Precision:", precision_score(y_test, y_pred_gnb))

Accuracy: 0.8694390715667312
Confusion Matrix:
 [[788 108]
 [ 27 111]]
Precision: 0.5068493150684932


In [ ]:
mnb.fit(x_train, y_train)
y_pred_mnb = mnb.predict(x_test)

print("MultinomialNB Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_mnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_mnb))
print("Precision:", precision_score(y_test, y_pred_mnb))
print("-" * 50)

MultinomialNB Results:
Accuracy: 0.9709864603481625
Confusion Matrix:
 [[896   0]
 [ 30 108]]
Precision: 1.0
--------------------------------------------------


In [ ]:
bnb.fit(x_train, y_train)
y_pred_bnb = bnb.predict(x_test)

print("BernoulliNB Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_bnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bnb))
print("Precision:", precision_score(y_test, y_pred_bnb))
print("-" * 50)

BernoulliNB Results:
Accuracy: 0.9835589941972921
Confusion Matrix:
 [[895   1]
 [ 16 122]]
Precision: 0.991869918699187
--------------------------------------------------


In [ ]:
import pickle
pickle.dump(tfidf,open("vectorizer.pkl","wb"))
pickle.dump(mnb,open("model.pkl","wb"))